import modals from "./modules/modals";
import sliders from "./modules/sliders";
import forms from "./modules/forms";
import mask from "./modules/mask";
import checkTextInputs from "./modules/checkTextInputs";
import showMoreStyles from "./modules/showMoreStyles";
import calc from "./modules/calc";
import filter from "./modules/filter";
import pictureSize from "./modules/pictureSize";
import accordion from "./modules/accordion";
import burger from "./modules/burger";
import scrolling from "./modules/scrolling";
import drop from "./modules/drop.js";
import { WOW } from "wowjs";

window.addEventListener("DOMContentLoaded", () => {
  "use strict";
  const wow = new WOW({ live: false });
  wow.init();
  modals();
  sliders(".feedback-slider-item", "", ".main-prev-btn", ".main-next-btn");
  sliders(".main-slider-item", "vertical");
  forms();
  mask(`[name="phone"]`);
  checkTextInputs(`[name="name"]`);
  checkTextInputs(`[name="message"]`);
  showMoreStyles(".button-styles", "#styles .row");
  calc();
  filter();
  pictureSize(".sizes-block");
  accordion(".accordion-heading", ".accordion-block");
  burger(".burger-menu", ".burger");
  scrolling(`a[href="#styles"]`);
  scrolling(`a[href="#portfolio"]`);
  scrolling(`a[href="#often-questions"]`);
  scrolling(`a[href="#scheme"]`);
  scrolling(`a[href="#footer"]`);
  drop();
});
